### ISSUE TITLE
LICENSE file was incomplete

### ISSUE THREAD

**Issue by jserv** [neozeed/xMach#2]
I attempted to download from [ xmach v0.0.1](https://sourceforge.net/projects/xmach/files/xmach/0.0.1/) and found some copyright notice as following:
> Mach Operating System
> Copyright (c) 1991,1990,1989,1988 Carnegie Mellon University

However, in this repository, there was no explicit information on CMU or prior efforts.

**Comment by neozeed** [comment]
build it and enumerate them all then.

**Comment by jserv** [comment]
> build it and enumerate them all then.

Why not making a comprehensive list of licensing terms and copyright holders in top-level directory?

**Comment by neozeed** [comment]
Because it’s 1am. And a dead end thing I just stashed to pull if I get time in the next 10-20 years and I wanted a place for my build notes.

It’s also why I welcome you to dmesg it, and enumerate all the files to chase the origin of each one.

you have the time so do a pull request once you’ve audited it all.

It’s obsolete and an evolutionary dead end, do you even intend to build it and run it?


What’s your real goal?  Are you actually interested in running xMach?!

**Comment by neozeed** [comment]
```
find ./ -type f -exec awk 'BEGIN{RS=ORS="/";FS=OFS="/\n"}/opyright/' {} \; > ../mk4-copy.txt
```

since it's based on L4 from Utah which is using Mach 3.0

[mk4-Copyright blocks.txt](https://github.com/neozeed/xMach/files/7081605/mk4-Copyright.blocks.txt)
[mk4-Copyright.txt](https://github.com/neozeed/xMach/files/7081606/mk4-Copyright.txt)
